ebook_metadata:
  title: ༄༅། །དིང་རི་བ་ཆེན་པོ་འཆི་མེད་བློ་གྲོས་བརྟན་པའི་རྣམ་ཐར་ཡོན་ཏན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། སྨིན་གླིང་ལོ་ཆེན་དྷརྨ་ཤྲཱི།
  sku: LS-ZHI-05-02
  layers:
  - book_title
  - author
  - chapter_title
web_metadata:
  title:
    en: The Light of Good Qualities:A Biography of Chime Lodro Tenpa, the Great Master
      from Dingri
    bo: དིང་རི་བ་ཆེན་པོ་འཆི་མེད་བློ་གྲོས་བརྟན་པའི་རྣམ་ཐར་ཡོན་ཏན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།
  collection:
    en: Zhije Series–  Book 5-2
    bo: ཞི་བྱེད།–  དེབ། ༥-༢
  author:
    en: Lochen Dharmashri
    bo: དྷརྨ་ཤྲཱི།
  pusblisher:
    en: Dingri Langkor Zhijed Ling
    bo: དིང་རི་གླང་སྐོར་ཞི་བྱེད་གླིང་།
  sku: LS-ZHI-05-02
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LS-ZHI-05-02.epub
  description:
    en: ''
    bo: ''
